name: Run Unit Test via Pytest

on: [push]

#Here we define the name, the trigger for the workflow and some boilerplate including the type of GitHub Actions runner
#  and what version of Python to run on.
#Triggers can be events like a Pull Request, merge to x branch, release tag and so on.

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --format=github --target-version=py310 .
        continue-on-error: true
      - name: Test with pytest
        run: |
          coverage run -m pytest  -v -s
      - name: Generate Coverage Report
        run: |
          coverage report -m
